### PR TITLE
Remove deprecated functions, templatize, speedup, add compensation factors

### PR DESCRIPTION
**Pull request by HorstBaerbel**
Thanks for maintaining the library! I've taken some time to:
* Revamp the library by removing the deprecated functionality and make it a template, so float or double can be used. float is enough for most use cases and is much faster (~70% in my case on a ESP32). It is also now header-only.
* Added an option to specify a cache array for window weighing factors as this also speeds up windowing() calls significantly (~50% gain in my case). 
* Added some experimental #defines to enable math approximisations to further speed up compute(), windowing() and complexToMagnitude() (~50% gain for me).
* Overall I went from ~16-17 ms per frame down to ~1.7 ms with the same results (512 ADC samples to 16-bar spectrum on ESP32).
* Added windowing compensation factors (see issue #40).
* Added an example for the new functionality and #defines.
* Updated the README information and formatting.
* Updated library.*, keywords.txt and changeLog.txt.

I coined the version 1.9.0, as it's breaking the API but there might be some changes necessary to call it 2.0.0 (maybe you want to put thins into a testing branch first). I tried compiling all examples in the Arduino-IDE (1.8.10) and Visual Studio Code + Arduino Extension, but haven't used the library from straight C. I wonder how that worked before, because it was C++ anyways, but If you tell me how to check that, I can try.

### CODE REVIEW

**Comment by kosme** [comment]
I like several of the things you implemented, they look quite useful. But as stated on issue #32 , some users want to continue using pointers to the data in order to control memory usage and use the stored data for other purposes. You removed all of those functions, which breaks it for those users. Also, since you changed the naming of almost everything, the API would be broken for all of the users. Therefore I cannot merge your code in its current state into the main branch.

**Comment by HorstBaerbel** [comment]
Ok, I haven't read issue #32. The functions taking pointers were marked as deprecated and issued messages stating that, that's why I removed them. The library still does not allocate any memory (except static variables like before), you pass in the pointers in the constructor. When the memory is deallocated ouside of the library, it is freed and the library does not care. I don't see how you can call `compute()` or `complexToMagnitude()` either way (forward or reverse) without having (or passing in) a valid `vImag` array. All other functions don't use `vImag`, so you can just deallocate it and go on using the library without issues.  

What I would propose:
* I add a function `void setData(T *vReal, T *vImag);` (set new pointers. pick a name) or `void swapRealImag();` (swap internal pointers. pick a name) to enable users to switch / swap / replace data pointers however they like. This seems to suffice for me. I will ask in #32 for the use case.
* I would not recommend making the function name "`PascalCase()`" (start uppercase) again. This is somewhat of a religious topic, but most people seem to agree "`snake_case()`" or "`camelCase()`" is the [correct way](https://stackoverflow.com/questions/1776291/function-names-in-c-capitalize-or-not).
* I can update the README with a "migration guide"  from 1.x to 2.x, stating what people need to do.
* Split into a new library aka "arduinoFFT++", though I'd hate fragmenting the library landscape like that.

As I was writing: I wasn't asking you to merge this into the main branch now, but maybe put into a feature branch for version 2.0.

**Comment by kosme** [comment]
Code merged in to a new branch called Develop

**Comment by HorstBaerbel** [comment]
@kosme Is this gonna rot in develop now or are you actually gonna do something with it? I don't mean to sound offensive, but it is rather disappointing to work on something and then just see it go to waste. If you say you're not gonna use it, I'm gonna make a proper fork, no sweat, but I kind of hate the fragmentation on GitHub as-is...

**Comment by kosme** [comment]
@HorstBaerbel I must confess that when you provided the code, I could not understand what was going on with it. Then, after the fragmentation, I neglected reviewing it. Now that I finally understand templating and such, I have finally been doing that for the last couple of days and I have some questions about some decisions you made when writing it.

1. Since AVR chips don't make a difference between `float` and `double` data types and other chips can easily accommodate the extra space required when using `double` variables and benefit from the extra resolution and precision, could you provide an example of when would a `float` data type be preferred using the current code implementation?
2. How did you manage to compile your code for an AVR chip using the FFT_SQRT_APPROXIMATION definition? Because as far as I can see, it can't be done.

**Comment by HorstBaerbel** [comment]
> @HorstBaerbel I must confess that when you provided the code, I could not understand what was going on with it. Then, after the fragmentation, I neglected reviewing it. Now that I finally understand templating and such, I have finally been doing that for the last couple of days and I have some questions about some decisions you made when writing it.

The branches have diverged a bit now, but it should not be too hard to include the new stuff from master here (or the other way around). I intended to do this at some point, but atm my motivation is low and I don't have much time...

>     1. Since AVR chips don't make a difference between `float` and `double` data types and other chips can easily accommodate the extra space required when using `double` variables and benefit from the extra resolution and precision, could you provide an example of when would a `float` data type be preferred using the current code implementation?

My original intention was that the code was using much too much CPU on the ESP32, which is already quite powerful. The ESP has a FPU to calculate floating-point math in hardware, but only for float values (32bit), NOT double values (64bit). This is the case for a couple of architectures where float is massively faster (see above, 1/3 runtime, for the FFT alone).
Then there's the question of RAM, which is always low on smaller chips. If you don't need the increased precision double provides, why pay the cost for it?! For a simple audio application float might be enough and it uses less than half the space...

With the template you can decide for yourself what you want.

I'm also [not so sure float and double are still the same on AVR-GCC](https://gcc.gnu.org/wiki/avr-gcc) everywhere.
 
>     2. How did you manage to compile your code for an AVR chip using the FFT_SQRT_APPROXIMATION definition? Because as far as I can see, it can't be done.

Can you tell me what the problem is? I don't remember if I actually tried it on an AVR, but I trust myself to at least compile for it...

If I can be of further help please tell me. I'd be happy not having to use my own fork for my audio projects...

**Pull request closed without merging**
